[workspace]
authors = ["liar <yyxxyyzero@163.com>"]
channels = ["conda-forge"]
name = "SigWorks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.13"
rich = ">=14.0"
scikit-learn = ">=1.7"
scikit-image = ">=0.25.0"

[pypi-dependencies]
torch = { version = ">=2.8", index = "https://download.pytorch.org/whl/cu129" }
torchvision = { version = ">=0.23.0", index = "https://download.pytorch.org/whl/cu129" }
torch_geometric = { version = ">=2.6.0" }
pyg_lib = { url = "https://data.pyg.org/whl/torch-2.8.0%2Bcu129/pyg_lib-0.5.0%2Bpt28cu129-cp313-cp313-linux_x86_64.whl"}
torch_cluster = { url = "https://data.pyg.org/whl/torch-2.8.0%2Bcu129/torch_cluster-1.6.3%2Bpt28cu129-cp39-cp39-linux_x86_64.whl" }
torch_scatter = { url = "https://data.pyg.org/whl/torch-2.8.0%2Bcu129/torch_scatter-2.1.2%2Bpt28cu129-cp39-cp39-linux_x86_64.whl" }
torch_sparse = { url = "https://data.pyg.org/whl/torch-2.8.0%2Bcu129/torch_sparse-0.6.18%2Bpt28cu129-cp39-cp39-linux_x86_64.whl" }
torch_spline_conv = { url = "https://data.pyg.org/whl/torch-2.8.0%2Bcu129/torch_spline_conv-1.2.2%2Bpt28cu129-cp39-cp39-linux_x86_64.whl" }

#for sigver
visdom_logger = { git = "https://github.com/luizgh/visdom_logger.git" }
sigver = { git = "https://github.com/luizgh/sigver.git" }